### ISSUE TITLE
[Bug] Can "receive" `new_webcash` twice

### ISSUE THREAD

**Issue by callebtc** [juzybits/webcasa#2]
If you receive webcash, the "Send" tab shows the newly issued webcash as `new_webcash`.

The wallet allows the user to copy it and receive it again which shouldn't be possible. It is then falsely reflected in the balance. From there on, the user can't send any more webcash since the wallet now presumably has a bad state.

Reproduce:

* Have x webcash
* Send 1 webcash (Balance: x-1)
* Receive that 1 webcash (Balance: x)
* Copy `new_webcash` and receive it
* Balance: x+1

†

**Comment by juzybits** [comment]
Thanks for the bug report! It is fixed now.

Explanation:
The balance correctly decreases when you use the "Send" function. "Send" is how the wallet knows that you're taking a secret out of it, so it knows to decrease the balance. However, if instead of using "Send", you grab the new webcash directly from the wallet and then use "Receive" to insert it back in, the wallet gets confused because it assumes that secret came from somewhere else.

I fixed this in two ways:
1) When inserting a secret via "Receive", do not show the new secret to the user to avoid confusion.
2) If the user still tries to insert a secret that's already in the wallet, show an error.
